### PR TITLE
Rename translation strings for numbers [LEI-217]

### PR DESCRIPTION
**Pull request by samanehsan**
Change translation strings for numbers from "numberN" to "N"

Requires https://github.com/CenterForOpenScience/exp-addons/pull/149

### CODE REVIEW

**Comment by samanehsan** [comment]
The answer to the [first question](https://github.com/samanehsan/exp-addons/blob/bf8eca8d82c293ef36d41da8700b349aa9edc8a1/exp-player/addon/components/exp-overview/component.js#L138) in the exp-overview form is still getting serialized as a string. @abought, do you think that has something to do with the select drop down?

**Comment by abought** [comment]
As discussed internally, this will work for now, but in the future we shouldn't rely on a coupling between content and presentation this way.

Since this changes the names of keys in the translation file, does this trigger any change in ongoing translation work? 

I encourage us to try to finalize and clean up as many translation string names as possible before this goes out to others- it will be harder to make changes once we have to maintain translation files.

**Comment by samanehsan** [comment]
Translation work has not started as far as I know. I'm going to review the translation strings today to see if there's anything that could be cleaned up.

They don't need to translate numbers, so those strings are not in the spreadsheet. However, the templates expect a translation string and it's easy enough to add in those translation strings with `format_json.py` rather than having to check the value of each option and deciding whether or not it should be translated.

**Comment by abought** [comment]
Pass complete. I have one question (for the companion PR) before this is merged; feel free to return the ticket to me when you think it's ready.

**Pull request merged**
